[server]
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 200

[theme]
base = "dark"
primaryColor = "#FF4B4B"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#262730"
textColor = "#FAFAFA"
